### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lagru** [scientific-python/docstub#9]
A rough work in progress roadmap for docstub:

#### v0.3

- [x] Add basic CI tests
- [ ] Errors and warnings point to parsed source if possible
- [ ] Report statistics at the end: error count, file count, runtime, ...
- [ ] Add basic caching of static analysis
- [ ] CI testing with mypy
- [ ] Explore parallelization

#### v0.x

- [ ] "Dogfooding" -- publish and distribute stubs for docstub
- [ ] Add support for grammar & transformation extensions
- [ ] Support inline type annotations
- [ ] Support docstring styles other than NumPyDoc (already supported)

#### v1.0

- [ ] Actively used by major projects
